# Aamv Site
aamv_site:
    resource: "@AamvSiteBundle/Resources/config/routing.yml"
    prefix:   /

# Aamv User
aamv_user:
    resource: "@AamvUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Aamv Admin
aamv_admin_aamv:
    resource: "@AamvSiteBundle/Resources/config/routing_admin.yml"
    prefix: /admin