security:
    encoders:
        default:
            algorithm: bcrypt
        legacy:
            id: password_encoder.legacy

    role_hierarchy:
        ROLE_PARENT:      ROLE_PARENT
        ROLE_ASSISTANTE:  ROLE_ASSISTANTE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[_username]
                password_parameter: login[_password]
            logout:
                invalidate_session: true
                path: /logout
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
                remember_me_parameter: login[_remember_me]

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/services/ads/create, roles: [ROLE_ASSISTANTE, ROLE_PARENT] }
        - { path: ^/manage, roles: [ROLE_ASSISTANTE, ROLE_PARENT] }
