security:
    encoders:
        default:
            algorithm: bcrypt
        legacy:
            id: password_encoder.legacy

    role_hierarchy:
        ROLE_PARENT:    ROLE_PARENT
        ROLE_TRAINEE:   ROLE_TRAINEE
        ROLE_ASSISTANT: ROLE_ASSISTANT
        ROLE_MEMBER:    ROLE_ASSISTANT
        ROLE_ADMIN:
            - ROLE_PARENT
            - ROLE_ASSISTANT
            - ROLE_MEMBER
            - ROLE_TRAINEE

    providers:
        user:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[_email]
                password_parameter: login[_password]
            logout:
                invalidate_session: true
                path: /logout
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
                remember_me_parameter: login[_remember_me]

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/services/ads/parent, role: ROLE_MEMBER }
        - { path: ^/files/disponibilities, role: ROLE_MEMBER }
        - { path: ^/services/ads/create, roles: [ROLE_ASSISTANT, ROLE_PARENT, ROLE_TRAINEE] }
        - { path: ^/manage/ad, roles: [ROLE_MEMBER, ROLE_PARENT, ROLE_TRAINEE] }
        - { path: ^/manage, roles: [ROLE_ASSISTANT, ROLE_PARENT, ROLE_TRAINEE] }
