sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:

sonata_admin:
    title: Aamv
    templates:
        layout: AamvSiteBundle::sonata_admin_base_layout.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Bienvenue sur la page d'administration du site AAMV</h2>
                        <p>Vous allez ici pouvoir gérer <code>toutes</code> les informations importantes du site :</p>
                        <ul>
                            <li>News</li>
                            <li>Outils</li>
                            <li>Disponibilités des assistantes</li>
                        </ul>
    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - vendor/smalot-bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css
        javascripts:
            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - vendor/smalot-bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js
            - bundles/aamvsite/js/Admin/default.js
sonata_intl:
    timezone:
        locales:
            fr:    Europe/Paris
