sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Aamv
    templates:
        layout: AamvSiteBundle::sonata_admin_base_layout.html.twig

sonata_intl:
    timezone:
        locales:
            fr:    Europe/Paris
