services:
    sonata.admin.news:
        class: Aamv\Bundle\SiteBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "News" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.tools:
        class: Aamv\Bundle\SiteBundle\Admin\ToolsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Outils" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Tools
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.disponibilities:
        class: Aamv\Bundle\SiteBundle\Admin\DisponibilitiesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Informations", label: "Disponibilités" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Disponibility
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.events:
        class: Aamv\Bundle\SiteBundle\Admin\EventsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Evénements", label: "Evénements" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.event_pictures:
        class: Aamv\Bundle\SiteBundle\Admin\EventPicturesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Evénements", label: "Photos d'évènements" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\EventPicture
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]