services:
    sonata.admin.news:
        class: Aamv\Bundle\SiteBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "News" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.context ] ]
    sonata.admin.tools:
        class: Aamv\Bundle\SiteBundle\Admin\ToolsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tools" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Tools
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.context ] ]