services:
    sonata.admin.news:
        class: Aamv\Bundle\SiteBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "News" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\News
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.tools:
        class: Aamv\Bundle\SiteBundle\Admin\ToolsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tools" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Tools
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.events:
        class: Aamv\Bundle\SiteBundle\Admin\EventsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Events" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\Event
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]
    sonata.admin.event_pictures:
        class: Aamv\Bundle\SiteBundle\Admin\EventPicturesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Event Pictures" }
        arguments:
            - ~
            - Aamv\Bundle\SiteBundle\Entity\EventPicture
            - ~
        calls:
            - [ setTranslationDomain, [ AamvSiteBundle ] ]
            - [ setSecurityContext, [ @security.token_storage ] ]