# Apis
aamv_site_api_cities:
    path: /api/cities/get/{name}
    defaults: { _controller: AamvSiteBundle:Api/CitiesApi:get}
    options:
        expose: true

# Homepage
aamv_site_homepage:
    path:     /
    defaults: { _controller: AamvSiteBundle:Homepage:index }

aamv_site_homepage_news:
    path:     /news/{page}
    defaults: { _controller: AamvSiteBundle:Homepage:index }

aamv_site_new:
    path:     /new/{id}
    defaults: { _controller: AamvSiteBundle:Homepage:new }

# Services
aamv_site_services_ads:
    path:     /services/ads/{type}/{city}/{neighborhood}/{page}
    defaults: { _controller: AamvSiteBundle:Services:ads, page: 1, city: none, neighborhood: none }
    options:
        expose: true

aamv_site_services_ad_create:
    path:     /services/ad/create
    defaults: { _controller: AamvSiteBundle:Services:createAd }

aamv_site_services_ad_show:
    path:     /services/ad/{id}
    defaults: { _controller: AamvSiteBundle:Services:showAd }

aamv_site_services_disponibilities:
    path:     /services/disponibilities
    defaults: { _controller: AamvSiteBundle:Services:disponibilities }

aamv_site_services_outils:
    path:     /services/outils
    defaults: { _controller: AamvSiteBundle:Services:outils }

# Divers
aamv_site_divers_articles:
    path:     /divers/articles
    defaults: { _controller: AamvSiteBundle:Divers:articles }

aamv_site_divers_questions_reponses:
    path:     /services/questions_reponses
    defaults: { _controller: AamvSiteBundle:Divers:questionsReponses }

aamv_site_divers_addresses:
    path:     /divers/addresses
    defaults: { _controller: AamvSiteBundle:Divers:addresses }

aamv_site_divers_sites:
    path:     /divers/sites
    defaults: { _controller: AamvSiteBundle:Divers:sites }

# Association
aamv_site_association_presentation:
    path:     /association/presentation
    defaults: { _controller: AamvSiteBundle:Association:presentation }

aamv_site_association_join:
    path:     /association/join
    defaults: { _controller: AamvSiteBundle:Association:join }

aamv_site_association_photos:
    path:     /association/photos
    defaults: { _controller: AamvSiteBundle:Association:photos }

aamv_site_association_about_us:
    path:     /association/about_us
    defaults: { _controller: AamvSiteBundle:Association:about_us }

# Contacts
aamv_site_contacts:
    path:     /contacts
    defaults: { _controller: AamvSiteBundle:Contacts:index }

# Management
aamv_site_manage_account:
    path:     /manage/account
    defaults: { _controller: AamvSiteBundle:Management:account }

aamv_site_manage_ads:
    path:     /manage/ads
    defaults: { _controller: AamvSiteBundle:Management:ads }

aamv_site_manage_disponibilities:
    path:     /manage/disponibilities
    defaults: { _controller: AamvSiteBundle:Management:disponibilities }
