# Homepage
aamv_site_homepage:
    path:     /
    defaults: { _controller: AamvSiteBundle:Homepage:index }

# Pages News
aamv_site_news_association:
    path:     /news/association
    defaults: { _controller: AamvSiteBundle:News:association }

aamv_site_news_reunions:
    path:     /news/reunion
    defaults: { _controller: AamvSiteBundle:News:reunion }

# Pages L'Association
aamv_site_association_presentation:
    path:     /association/presentation
    defaults: { _controller: AamvSiteBundle:Association:presentation }
    
aamv_site_association_historique:
    path:     /association/reunion
    defaults: { _controller: AamvSiteBundle:Association:historique }
    
aamv_site_association_objectifs:
    path:     /association/objectifs
    defaults: { _controller: AamvSiteBundle:Association:objectifs }
    
aamv_site_association_services_am:
    path:     /association/services_am
    defaults: { _controller: AamvSiteBundle:Association:servicesam }
    
aamv_site_association_services_parents:
    path:     /association/services_parents
    defaults: { _controller: AamvSiteBundle:Association:servicesparents }
    
aamv_site_association_adhesion:
    path:     /association/adhesion
    defaults: { _controller: AamvSiteBundle:Association:adhesion }
