# Apis

aamv_site_api_cities:
    path: /api/cities/get/{name}
    defaults: { _controller: AamvSiteBundle:Api/CitiesApi:get}
    options:
        expose: true

# Homepage
aamv_site_homepage:
    path:     /
    defaults: { _controller: AamvSiteBundle:Homepage:index }

aamv_site_homepage_news:
    path:     /news/{page}
    defaults: { _controller: AamvSiteBundle:Homepage:index }

aamv_site_new:
    path:     /new/{id}
    defaults: { _controller: AamvSiteBundle:Homepage:new }

# Pages Services
aamv_site_services_ads:
    path:     /services/ads/{type}/{city}/{neighborhood}/{page}
    defaults: { _controller: AamvSiteBundle:Services:ads, page: 1, city: none, neighborhood: none }
    options:
        expose: true

aamv_site_services_ad_create:
    path:     /services/ad/create
    defaults: { _controller: AamvSiteBundle:Services:createAd }

aamv_site_services_ad_show:
    path:     /services/ad/{id}
    defaults: { _controller: AamvSiteBundle:Services:showAd }

aamv_site_services_management:
    path:     /services/management
    defaults: { _controller: AamvSiteBundle:Services:management }

aamv_site_services_outils:
    path:     /services/outils
    defaults: { _controller: AamvSiteBundle:Services:outils }

aamv_site_services_questions_reponses:
    path:     /services/questions_reponses
    defaults: { _controller: AamvSiteBundle:Services:questionsReponses }

# Pages Divers
aamv_site_divers_articles:
    path:     /divers/articles
    defaults: { _controller: AamvSiteBundle:Divers:articles }

aamv_site_divers_adresses:
    path:     /divers/adresses
    defaults: { _controller: AamvSiteBundle:Divers:adresses }

aamv_site_divers_sites_utiles:
    path:     /divers/sites
    defaults: { _controller: AamvSiteBundle:Divers:sites }

# Pages L'Association
aamv_site_association_presentation:
    path:     /association/presentation
    defaults: { _controller: AamvSiteBundle:Association:presentation }

aamv_site_association_photos:
    path:     /association/photos
    defaults: { _controller: AamvSiteBundle:Association:photos }

aamv_site_association_parle:
    path:     /association/parle
    defaults: { _controller: AamvSiteBundle:Association:parle }

# Pages Contacts
aamv_site_contacts:
    path:     /contacts
    defaults: { _controller: AamvSiteBundle:Contacts:index }