aamv_site_homepage:
    path:     /
    defaults: { _controller: AamvSiteBundle:Homepage:index }
    
aamv_site_new_association:
    path:     /
    defaults: { _controller: AamvSiteBundle:News:association }
    
aamv_site_new_reunion:
    path:     /
    defaults: { _controller: AamvSiteBundle:News:reunion }
