# Homepage
aamv_site_homepage:
    path:     /
    defaults: { _controller: AamvSiteBundle:Homepage:index }

# Pages News
aamv_site_news:
    path:     /news
    defaults: { _controller: AamvSiteBundle:News:index }

# Pages Services
aamv_site_services_annonces:
    path:     /services/annonces
    defaults: { _controller: AamvSiteBundle:Services:annonces }

aamv_site_services_outils:
    path:     /services/outils
    defaults: { _controller: AamvSiteBundle:Services:outils }

aamv_site_services_questions_reponses:
    path:     /services/questions_reponses
    defaults: { _controller: AamvSiteBundle:Services:questionsReponses }

# Pages Divers
aamv_site_divers_articles:
    path:     /divers/articles
    defaults: { _controller: AamvSiteBundle:Divers:articles }

aamv_site_divers_adresses:
    path:     /divers/adresses
    defaults: { _controller: AamvSiteBundle:Divers:adresses }

aamv_site_divers_sites_utiles:
    path:     /divers/sites
    defaults: { _controller: AamvSiteBundle:Divers:sites }

# Pages L'Association
aamv_site_association_presentation:
    path:     /association/presentation
    defaults: { _controller: AamvSiteBundle:Association:presentation }

aamv_site_association_photos:
    path:     /association/photos
    defaults: { _controller: AamvSiteBundle:Association:photos }

aamv_site_association_parle:
    path:     /association/parle
    defaults: { _controller: AamvSiteBundle:Association:parle }

# Pages Contacts
aamv_site_contacts:
    path:     /contacts
    defaults: { _controller: AamvSiteBundle:Contacts:index }

###############
#    Admin    #
###############

# Admin News
aamv_admin_news:
    path:   /admin/news
    defaults: { _controller: AamvSiteBundle:Admin/NewsAdmin:index }