aamv_admin_dashboard:
    path:     /
    defaults: { _controller: AamvAdminBundle:Dashboard:show }

# Admin News
aamv_admin_news:
    path:   /news/{page}
    defaults: { _controller: AamvSiteBundle:Admin/NewsAdmin:index, page: 1 }